SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

--- BatchJob
CREATE TABLE [dbo].[BatchJob](
	[JobName] [varchar](100) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[LastRun] [datetime] NOT NULL,
 CONSTRAINT [PK_BatchJob_1] PRIMARY KEY CLUSTERED 
(
	[JobName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO