SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BatchStep](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[StepName] [nvarchar](100) NOT NULL,
	[StepIndex] [bigint] NOT NULL,
	[NumberOfItemsProcessed] [int] NOT NULL,
	[JobName] [varchar](100) NOT NULL,
	[LastRun] [datetime] NOT NULL,
 CONSTRAINT [PK_BatchStep] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BatchStep]  WITH CHECK ADD  CONSTRAINT [FK_BatchStep_BatchJob] FOREIGN KEY([JobName])
REFERENCES [dbo].[BatchJob] ([JobName])
GO

ALTER TABLE [dbo].[BatchStep] CHECK CONSTRAINT [FK_BatchStep_BatchJob]
GO